using Microsoft.Graph;
using Microsoft.Identity.Client;
using Microsoft.Identity.Web;
using System.Diagnostics;
using System.Net.Http.Headers;

namespace ESL.Mvc.Services
{
    /// <summary>
    /// Contains a set of methods that showcase how to utilize the MS Graph SDK methods properly with MSAL
    /// https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/5-WebApp-AuthZ/5-1-Roles/Services/GraphHelper.cs
    /// </summary>
    public class GraphHelper
    {
        private readonly GraphServiceClient _graphServiceClient;
        private readonly MicrosoftIdentityConsentAndConditionalAccessHandler _consentHandler;
        private string[] _graphScopes;
        private readonly int _graphCollectionMaxRows = 50;

        /// <summary>
        /// Initializes a new instance of the <see cref="GraphHelper"/> class.
        /// </summary>
        /// <param name="httpContext">The HTTP context.</param>
        /// <param name="graphScopes">The graph scopes.</param>
        /// <exception cref="System.NullReferenceException">
        /// The GraphServiceClient has not been added to the services collection during the ConfigureServices()
        /// or
        /// The MicrosoftIdentityConsentAndConditionalAccessHandler has not been added to the services collection during the ConfigureServices()
        /// </exception>
        /// <autogeneratedoc />
        public GraphHelper(HttpContext httpContext, string[] graphScopes)
        {
            var services = httpContext.RequestServices;

            this._graphServiceClient = (GraphServiceClient)services.GetService(typeof(GraphServiceClient));
            if (this._graphServiceClient == null) throw new NullReferenceException("The GraphServiceClient has not been added to the services collection during the ConfigureServices()");

            this._consentHandler = (MicrosoftIdentityConsentAndConditionalAccessHandler)services.GetService(typeof(MicrosoftIdentityConsentAndConditionalAccessHandler));
            //if (this._consentHandler == null) throw new NullReferenceException("The MicrosoftIdentityConsentAndConditionalAccessHandler has not been added to the services collection during the ConfigureServices()");

            this._graphScopes = graphScopes;
        }

        /// <summary>
        /// Calls the MS Graph /me endpoint
        /// </summary>
        /// <returns></returns>
        public async Task<User> GetMeAsync()
        {
            return await CallGraphWithCAEFallback<User>(
                async () =>
                {
                    // Call /me
                    return await _graphServiceClient.Me.Request().GetAsync();
                });
        }

        /// <summary>
        /// Calls the MS Graph /me/photo endpoint
        /// </summary>
        /// <returns></returns>
        public async Task<Stream> GetMyPhotoAsync()
        {
            try
            {
                return await
                    CallGraphWithCAEFallback<Stream>(
                        async () =>
                        {
                            // Call /me/Photo Api
                            return await _graphServiceClient.Me.Photo.Content.Request().GetAsync();
                        });
            }
            catch (ServiceException svcex) when (svcex.Error.Code == "ImageNotFound")
            {
                return default;
            }
        }

        /// <summary>
        /// Calls the MS Graph /me/photo endpoint
        /// </summary>
        /// <returns></returns>
        public async Task<IEnumerable<Group>> GetMemberOfAsync()
        {
            return ProcessIGraphServiceMemberOfCollectionPage(
                await CallGraphWithCAEFallback<IUserMemberOfCollectionWithReferencesPage>(
                    async () =>
                    {
                        return await _graphServiceClient.Me.MemberOf.Request().GetAsync();
                    })
                );
        }

        /// <summary>
        /// Calls the MS Graph /me/photo endpoint
        /// </summary>
        /// <returns></returns>
        public async Task<IEnumerable<User>> GetUsersAsync()
        {
            return await CollectionProcessor<User>.ProcessGraphCollectionPageAsync(
                _graphServiceClient

                , await CallGraphWithCAEFallback<ICollectionPage<User>>(
                    async () =>
                    {
                        return await _graphServiceClient.Users.Request().GetAsync();
                    })

                , _graphCollectionMaxRows
            );
        }

        /// <summary>
        /// Calls a Microsoft Graph API, but wraps and handle a CAE exception, if thrown
        /// </summary>
        /// <typeparam name="T">The type of the object to return from MS Graph call</typeparam>
        /// <param name="graphAPIMethod">The graph API method to call.</param>
        /// <returns></returns>
        /// <exception cref="System.Exception">Unknown error just occurred. Message: {ex.Message}</exception>
        /// <autogeneratedoc />
        private async Task<T> CallGraphWithCAEFallback<T>(Func<Task<T>> graphAPIMethod)
        {
            try
            {
                return await graphAPIMethod();
            }
            catch (ServiceException ex) when (ex.Message.Contains("Continuous access evaluation resulted in claims challenge"))
            {
                try
                {
                    // Get challenge from response of Graph API
                    var claimChallenge = WwwAuthenticateParameters.GetClaimChallengeFromResponseHeaders(ex.ResponseHeaders);

                    _consentHandler.ChallengeUser(_graphScopes, claimChallenge);
                }
                catch (Exception ex2)
                {
                    _consentHandler.HandleException(ex2);
                }

                return default;
            }
        }

        /// <summary>
        /// Processes a page of users groups memberships .
        /// </summary>
        /// <param name="membersCollectionPage">First page having collection of directory roles and groups</param>
        /// <returns>List of groups</returns>
        private static List<Group> ProcessIGraphServiceMemberOfCollectionPage(IUserMemberOfCollectionWithReferencesPage membersCollectionPage)
        {
            try
            {
                List<Group> allGroups = new List<Group>();

                if (membersCollectionPage != null)
                {
                    do
                    {
                        // Page through results
                        foreach (DirectoryObject directoryObject in membersCollectionPage.CurrentPage)
                        {
                            //Collection contains directory roles and groups of the user.
                            //Checks and adds groups only to the list.
                            if (directoryObject is Group)
                            {
                                allGroups.Add(directoryObject as Group);
                            }
                        }

                        // are there more pages (Has a @odata.nextLink ?)
                        if (membersCollectionPage.NextPageRequest != null)
                        {
                            membersCollectionPage = membersCollectionPage.NextPageRequest.GetAsync().Result;
                        }
                        else
                        {
                            membersCollectionPage = null;
                        }
                    } while (membersCollectionPage != null);
                }

                return allGroups;
            }
            catch (ServiceException ex)
            {
                Console.WriteLine($"We could not process the group membership pages: {ex}");
                return null;
            }
        }
    }


    // https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/2-WebApp-graph-user/2-3-Multi-Tenant/Services/IMSGraphService.cs
    public interface IMSGraphService
    {
        Task<IEnumerable<User>> GetUsersAsync(string accessToken);
    }


    /// <summary>Provides helper methods built over MS Graph SDK</summary>
    /// <seealso cref="WebApp_MultiTenant_v2.Services.IMSGraphService" />
    public class MSGraphService : IMSGraphService
    {
        // the Graph SDK's GraphServiceClient
        private GraphServiceClient graphServiceClient;
        private IConfiguration configuration;
        private string[] _graphScopes;
        private readonly GraphServiceClient _graphServiceClient;
        private readonly MicrosoftIdentityConsentAndConditionalAccessHandler _consentHandler;


        public MSGraphService(IConfiguration configuration, IHttpContextAccessor httpContextAccessor)
        {
            this.configuration = configuration;

            var services = httpContextAccessor.HttpContext.RequestServices;

            this._graphServiceClient = (GraphServiceClient)services.GetService(typeof(GraphServiceClient));
            if (this._graphServiceClient == null) throw new NullReferenceException("The GraphServiceClient has not been added to the services collection during the ConfigureServices()");

            this._consentHandler = (MicrosoftIdentityConsentAndConditionalAccessHandler)services.GetService(typeof(MicrosoftIdentityConsentAndConditionalAccessHandler));
            if (this._consentHandler == null) throw new NullReferenceException("The MicrosoftIdentityConsentAndConditionalAccessHandler has not been added to the services collection during the ConfigureServices()");

            this._graphScopes = configuration.GetValue<string>("GraphAPI:Scopes").Split(' ');
        }

        /// <summary>
        /// Gets the users in a tenant.
        /// </summary>
        /// <param name="accessToken">The access token for MS Graph.</param>
        /// <returns>
        /// A list of users
        /// </returns>
        public async Task<IEnumerable<User>> GetUsersAsync(string accessToken)
        {
            IGraphServiceUsersCollectionPage users = null;

            try
            {
                PrepareAuthenticatedClient(accessToken);

                // Using Graph SDK to get users, filtering by active ones and returning just id and userPrincipalName field
                users = await CallGraphWithCAEFallback<IGraphServiceUsersCollectionPage>(
                    async () =>
                    {
                        return await graphServiceClient.Users.Request().Filter($"accountEnabled eq true").Select("id, userPrincipalName").GetAsync();
                    });

                if (users?.CurrentPage.Count > 0)
                {
                    return users;
                }
            }
            catch (ServiceException e)
            {
                Debug.WriteLine("We could not retrieve the user's list: " + $"{e}");
                return null;
            }

            return users;
        }

        /// <summary>
        /// Calls a Microsoft Graph API, but wraps and handle a CAE exception, if thrown
        /// </summary>
        /// <typeparam name="T">The type of the object to return from MS Graph call</typeparam>
        /// <param name="graphAPIMethod">The graph API method to call.</param>
        /// <returns></returns>
        /// <exception cref="System.Exception">Unknown error just occurred. Message: {ex.Message}</exception>
        /// <autogeneratedoc />
        private async Task<T> CallGraphWithCAEFallback<T>(Func<Task<T>> graphAPIMethod)
        {
            try
            {
                return await graphAPIMethod();
            }
            catch (ServiceException ex) when (ex.Message.Contains("Continuous access evaluation resulted in claims challenge"))
            {
                try
                {
                    // Get challenge from response of Graph API
                    var claimChallenge = WwwAuthenticateParameters.GetClaimChallengeFromResponseHeaders(ex.ResponseHeaders);

                    _consentHandler.ChallengeUser(_graphScopes, claimChallenge);
                }
                catch (Exception ex2)
                {
                    _consentHandler.HandleException(ex2);
                }

                return default;
            }
        }

        /// <summary>
        /// Prepares the authenticated client.
        /// </summary>
        /// <param name="accessToken">The access token.</param>
        private void PrepareAuthenticatedClient(string accessToken)
        {
            /***
            //Microsoft Azure AD Graph API endpoint,
            'https://graph.microsoft.com'   Microsoft Graph global service
            'https://graph.microsoft.us' Microsoft Graph for US Government
            'https://graph.microsoft.de' Microsoft Graph Germany
            'https://microsoftgraph.chinacloudapi.cn' Microsoft Graph China
                ***/

            graphServiceClient = new GraphServiceClient(configuration.GetValue<string>("GraphAPI:Endpoint"),
                new DelegateAuthenticationProvider(
                    async (requestMessage) =>
                    {
                        await Task.Run(() =>
                        {
                            requestMessage.Headers.Authorization = new AuthenticationHeaderValue("bearer", accessToken);
                        });
                    }));
        }
    }
}
